name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.42.0
          - stable

    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.rust }}
      - run: rustup default ${{ matrix.rust }}
      - run: cargo test
